baseURL = "https://devopswithramya.com/"
title = "DevOps With Ramya"
theme = "congo"
defaultContentLanguage = "en"
[params]
  googleSiteVerification = "RnZKW1W7BrcUdtxCm25ACmaji5d74y6Ya_Qoitd_DYo"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
    #updated